### ISSUE TITLE
Crafting Recipe Not Working.

### ISSUE THREAD

**Issue by hxgonic** [Robocraft999/CreateGoggles#11]
This is an issue expressed by a couple server owners, including me, where no crafting grid, either in a crafting table nor inventory is able to craft create goggles. This worked fine before the 0.5.5 update, however after updating there is no recipe currently defined in this server. This is verified as even external mods such as JEI show that there is no longer any way to craft these items, whereas before it did. Is there a fix for this?

**Comment by Robocraft999** [comment]
Yeah sorry. I noticed that too. Was an issue with the datagen. They should be back in the next version

**Comment by hxgonic** [comment]
Ah okay, thank you.
