### ISSUE TITLE
SP / SMP crash after update create 

### ISSUE THREAD

**Issue by ptk2003** [Robocraft999/CreateGoggles#13]
forge: 40.2.9
create: 1.18.2-0.5.1.b
flywheel: 1.18.2-0.6.8.a
createplus: 1.18.2_v0.5.1a

Mod File: /C:/Users/admin/AppData/Roaming/.minecraft/mods/createplus-1.18.2_v0.5.1a.jar
	Failure message: Create Plus (createplus) encountered an error during the common_setup event phase
		java.lang.NoClassDefFoundError: com/simibubi/create/content/contraptions/goggles/GogglesItem

**Comment by Robocraft999** [comment]
same as #9 . Maybe I look into porting it back to 1.18.2. Maybe

**Comment by jovanblazek** [comment]
Same issue here (but on fabric) :wave: [crash report](https://pastebin.com/rXhpmyLa)
I know you owe us nothing, but please consider updating the mod to support create 0.5.1 on 1.18.2 🙏
It's the last release of crete for this version of mc.

**Comment by Robocraft999** [comment]
I changed my mind. Update for 1.18.2 is out now
