### ISSUE TITLE
crash with a modpack i made

### ISSUE THREAD

**Issue by MinecraftedGaming** [Robocraft999/CreateGoggles#14]
i made a modpack for myself with create and some other mods but it crashed before opening ever since I added a few mods (including this one) and I've disables mods and enables them til I had one left and it what this mod I have the modpack exported so you can do testing to find where the issue is (because I cant)
[Create+ 1.19.2.zip](https://github.com/Robocraft999/CreateGoggles/files/11994263/Create%2B.1.19.2.zip)

**Comment by MinecraftedGaming** [comment]
the attached file has modlist and settings

**Comment by brisingraerowing** [comment]
[Game Log from my pack](https://gist.github.com/brisingraerowing/107de7e8a709b2192da590dfd98670ae)

It looks like a redirect mixin has the wrong target name.

**Comment by The-Arcanian** [comment]
Ya seems like a mixin problem. @brisingraerowing and my logs both cite `org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Redirect annotation on getArmorSlotsProxy could not find any targets matching 'get' in com.simibubi.create.content.equipment.armor.BacktankUtil. Using refmap creategoggles-forge-refmap.json`

**Comment by Robocraft999** [comment]
I see. They renamed their methods and added the curio support themselves. I can upload a quick fix

**Comment by The-Arcanian** [comment]
Can confirm that it is fixed. Thank you for the quick turnaround. 😀
