### ISSUE TITLE
Compatibility issue with Forbidden and Arcanus [1.19.2]

### ISSUE THREAD

**Issue by zacski1** [Robocraft999/CreateGoggles#18]
When this mod is installed alongside "Forbidden and Arcanus", attempting to apply its eternal stella and view the smithing recipe for it in JEI causes the game to crash. Results should be easily reproducible with a small modlist.

- Architectury: 6.5.85-forge
- Create: 1.19.2-0.5.1.c
- Create Goggles: 1.19.2-0.5.5.c-[FORGE]
- JEI: 1.19.2-forge-11.6.0.1016
- Forbidden Arcanus: 1.19.2-2.1.3
- Valhesia Core: 1.19.2-0.5.0
- Forge: 43.2.20

Crash report containing the issue at hand: https://pastebin.com/vJwwmWTB

Stal111 was nice enough to explain the problem as well so hopefully it'll help with the bug squashing :)
stal111/Forbidden-Arcanus#356

**Comment by Robocraft999** [comment]
Thanks for the report. As Stal111 already told you, the NBT is clashing because i copied their system wirhout thinking about this problem. I'll fix it when im back from vacation. You could try to disable experimentalFeatures in the config. Maybe this works for now

**Comment by Robocraft999** [comment]
Nah. Should'nt work either. Sorry. Then you have to wait unfortunately

**Comment by zacski1** [comment]
No worries just wanted to bring it to light, it's not truly gamebreaking or anything so I don't feel there's a rush to solve it. Plus I'd feel bad if I took up your vacation with it. Appreciate the acknowledgement and swift response.

**Comment by SikiciBebek** [comment]
When is the next update coming out? ^^
