### ISSUE TITLE
When will be 1.20 supported?

### ISSUE THREAD

**Issue by SkyKingPX** [Robocraft999/CreateGoggles#19]
^

**Comment by Robocraft999** [comment]
I'm working on it. It is a bit harder than I thought (and flywheel didn't compile last time I checked)

**Comment by SkyKingPX** [comment]
Oh, ok.
(May I look in the code and try to understand it? I am learning how to make stuff for Minecraft 🙂)

**Comment by SkyKingPX** [comment]
When do you think it will be ready? @Robocraft999

**Comment by Robocraft999** [comment]
2-3 weeks maybe. Im still on vacation

**Comment by SkyKingPX** [comment]
Oh 🫤

**Comment by DadudeGaming** [comment]
@Robocraft999 do you know when the forge 1.20.1 will be supported?

**Comment by Robocraft999** [comment]
The thing is i am currently working on a feature that doesn't want to quite work. I don't know why but I probably release the port and then later add the feature. I try to release it this week ok?

**Comment by DadudeGaming** [comment]
Amazing Thanks
I am running a small server with my friends and this is the last mod i need to update to 1.20.1

**Comment by DadudeGaming** [comment]
also can't wait for the new feature

**Comment by Robocraft999** [comment]
Fabric is doing weird things and wont compile

**Comment by SkyKingPX** [comment]
Lol 😂

**Comment by DadudeGaming** [comment]
Any update on 1.20.1 forge? @Robocraft999

**Comment by DadudeGaming** [comment]
Also would it be possible to add a create Stuff and Additions brass jetpack backtank? IDK where to start. Also what mod software would i use to open the mod and code it?

**Comment by Robocraft999** [comment]
porting is done an uploaded

**Comment by SkyKingPX** [comment]
Good Job @Robocraft999 👍 
Next version will be 1.20.2 😂🥲

**Comment by DadudeGaming** [comment]
Nice
