### ISSUE TITLE
can not use this mod when using optifine

### ISSUE THREAD

**Issue by Beafty** [Robocraft999/CreateGoggles#20]
[latest.log](https://github.com/Robocraft999/CreateGoggles/files/12262152/latest.log)
mod list:
![image](https://github.com/Robocraft999/CreateGoggles/assets/40541355/e1022219-0973-4d2e-953c-217003b54043)

**Comment by GeorgeEbberson** [comment]
Just ran into this also, using CreateGoggles v0.5.5.c and Optifine 1.19.2 I2 (the same as @Beafty). See attached logs:
[creategoggles_optifine_crash.log](https://github.com/Robocraft999/CreateGoggles/files/12285369/creategoggles_optifine_crash.log)

**Comment by GeorgeEbberson** [comment]
Just ran into this also, using CreateGoggles v0.5.5.c and Optifine 1.19.2 I2 (same as @Beafty) on Forge 43.2.3. See attached logs:
[creategoggles_optifine_crash.log](https://github.com/Robocraft999/CreateGoggles/files/12285384/creategoggles_optifine_crash.log)

**Comment by awesomebossdj7** [comment]
Who the FUCK uses optifine still??? Use rubidium and oculus

**Comment by awesomebossdj7** [comment]
https://media.discordapp.net/attachments/560583846509281280/1035541105997000704/57BAE7EC-E093-4CF2-A83F-AA50237A7D91.gif
