### ISSUE TITLE
[1.19.2] Create 5.1c+ Netherite diving helmet loses lava immunity trait when goggled (Server only)

### ISSUE THREAD

**Issue by Hyperbuss** [Robocraft999/CreateGoggles#23]
The regular netherite diving helmet provides immunity to lava when worn alongside full netherite gear + netherite backtank, however the goggled variant this mod provides removes this feature and one becomes vaulerable  to lava again. I reckon a method to remove the goggles in-case of future nbt mixups occur, so players can somewhat "fix" it.

**Comment by Robocraft999** [comment]
Strange... When I tested it by myself it worked fine. I try to verify it again. And there is a method to remove the goggles by crushing the helmet. I should actually mention the recipes somewhere now that I think about it

**Comment by DadudeGaming** [comment]
This only happens on servers for some reason
I was testing alot and figured this out
tryna neth mine in lava and almost died

**Comment by DadudeGaming** [comment]
@Robocraft999

**Comment by DadudeGaming** [comment]
oh and also crushing it removes enchants

**Comment by Robocraft999** [comment]
> oh and also crushing it removes enchants

Thats not changeable and a bit of a tradeoff for removing the goggles

**Comment by DadudeGaming** [comment]
ah ok

**Comment by DadudeGaming** [comment]
I was just doing some testing and i found on servers it also does not generate ores exposed to lava lakes

**Comment by DadudeGaming** [comment]
![image](https://github.com/Robocraft999/CreateGoggles/assets/76189578/8960f3bf-5dd1-40a6-a985-0312136de425)

**Comment by DadudeGaming** [comment]
but this is server only. it works on singleplayer

**Comment by Robocraft999** [comment]
> This only happens on servers for some reason I was testing alot and figured this out tryna neth mine in lava and almost died

can confim. just tetsted it. The question is why

**Comment by Robocraft999** [comment]
Alright i found it. I upload it tomorrow

**Comment by OlHonder** [comment]
I'm having the same issue, what's the fix?

**Comment by DadudeGaming** [comment]
I started using a curios slot for the goggles as i have custom armor that does not support goggle helmets. Not sure why this world gen glitch happened but it should be fixed (or you could try generating a world in single player and moving the nether to a server
