### ISSUE TITLE
1.20.1 Not loading

### ISSUE THREAD

**Issue by DadudeGaming** [Robocraft999/CreateGoggles#25]
Crash report:
[crash-2023-10-18_16.30.32-fml.txt](https://github.com/Robocraft999/CreateGoggles/files/13033709/crash-2023-10-18_16.30.32-fml.txt)
Mod list:
Architectury Api
Create
Create Goggles
Using forge 47.2.1

**Comment by DadudeGaming** [comment]
Also this happens:
![image](https://github.com/Robocraft999/CreateGoggles/assets/76189578/14b60fef-f3fb-4d7d-b1c0-f1d6794e1720)

**Comment by DadudeGaming** [comment]
And this
![image](https://github.com/Robocraft999/CreateGoggles/assets/76189578/565f36a7-8837-4249-b99e-00654f673f8a)
(On forge 47.2.0 and below)

**Comment by Robocraft999** [comment]
This should be Forge only right?

**Comment by Robocraft999** [comment]
I uploaded a new version. if the error persists tell me here

**Comment by DadudeGaming** [comment]
Ok think it works but il do another test with my server tonight
if it works I will close this bug report

**Comment by DadudeGaming** [comment]
yep it works now
