### ISSUE TITLE
Backtanks dont work for some reason

### ISSUE THREAD

**Issue by Looxond** [Robocraft999/CreateGoggles#3]
Version: creategoggles-0.5.4[FORGE].jar

https://user-images.githubusercontent.com/29359853/233938307-3712b986-f665-48bd-8480-6a8807725749.mp4

Modlist: 
![image](https://user-images.githubusercontent.com/29359853/233937487-7ee98eaa-d4bf-47af-b36d-505e4ada5771.png)
![image](https://user-images.githubusercontent.com/29359853/233937594-29233d00-85f1-4e75-b1cf-a74988af8aae.png)
![image](https://user-images.githubusercontent.com/29359853/233937681-663d4bb6-bb34-4957-97d4-4e0578aabd53.png)

Im not sure what interaction is causing this to happen, my best bet is relics or just a forge moment

**Comment by badgeminer** [comment]
I have had the same issue, is is not relics causing that

**Comment by Robocraft999** [comment]
Ah I see. if you dont wear a diving or goggle diving helmet it doesnt work

**Comment by Looxond** [comment]
Yeah about that...

It doesnt work with goggles diving helmet
It doesnt work if the copper backtank is on the curius body slot

https://youtu.be/B40Z16HuZO8
https://youtu.be/7r-7J2YMPUk

**Comment by Barerock** [comment]
This is still not working as intended. Copper and other backtank do not go in curio slots.

**Comment by Robocraft999** [comment]
@Barerock #5 !
