### ISSUE TITLE
Bugged when leaving the world with goggles still in curious. 

### ISSUE THREAD

**Issue by Kaizuto** [Robocraft999/CreateGoggles#32]
The goggles wont be unequipped and the functions still work across all saves. 1.20.1 latest version.

[Bugged when creating a new world](https://cdn.discordapp.com/attachments/1129069799545241703/1203674383143411772/image.png?ex=65d1f420&is=65bf7f20&hm=23608a2b14e77acf1c6a3f83eb71fe07dceab351e0e780115eca5f5234c0d792&)

**Comment by Kaizuto** [comment]
Removing the mod fixes this.

**Comment by Robocraft999** [comment]
Its not a bug, it's a Feature. The second world is probably a creative world in which you have the goggles without having to wear them in creative mode. You can disable this in the client config.

**Comment by Kaizuto** [comment]
oh ok mb
