### ISSUE TITLE
Compatibility Issue After Update

### ISSUE THREAD

**Issue by Sonifluous** [Robocraft999/CreateGoggles#7]
After a Create update for 1.19.2, I've noticed that the Create Goggles mod calls for a version lower than the latest. I'm not sure if this is intended or if there's simply an update I'm not aware about, but decided to submit the issue regardless as I've seen other users with similar errors

**Comment by Robocraft999** [comment]
Yes that is correct. We addon developers got warned by a create developer that our addons will probably break with the update. As I don't want people accidentally breaking their stuff, I set a restriction. I try to put up an update as soon as possible.

**Comment by Darkmega18** [comment]
Thank you muchly. hopefully disabling it temporarily won't cause too much issues on my world. I haven't crafted anything from the mod yet anyways.

**Comment by Robocraft999** [comment]
Yes that is correct. We addon developers got warned by a create developer that our addons will probably break with the update. As I don't want people accidentally breaking their stuff, I set a restriction. I try to put up an update as soon as possible.

**Comment by Darkmega18** [comment]
you said that already.

**Comment by Robocraft999** [comment]
Ah yes, sorry.

**Comment by FishyBusinessYT** [comment]
Any updates on this issue? Just ascking because we got an update 2 days  ago, but I'm not smart enough to deduce it by myself.

**Comment by Robocraft999** [comment]
The new version is a beta for the 0.5.1 version. It is mostly fine but leather has no color and the goggle diving helmet does not work for now and has a bugged texture. The goggle helmets and the backtanks provide their function fine as I'm aware. If you find more bugs feel free to report them

**Comment by Robocraft999** [comment]
I close this now as there is a release
