### ISSUE TITLE
Diving helmet not working

### ISSUE THREAD

**Issue by Proxwian** [Robocraft999/CreateGoggles#8]
Minecraft version 1.18.2
Forge 40.2.4
createplus-1.18.2_v0.5.1a.jar

![image](https://github.com/Robocraft999/CreateGoggles/assets/31781674/4a0f0b24-8f03-40a9-b71f-c3d31f4a87b1)

Player has helmet and create backtank, but oxygen keep depleting underwater

**Comment by Robocraft999** [comment]
That is correct. On this version minecraftversion it didn't work. Unfortunately 1.18.2 is discontinued so I won't fix it. Sorry

**Comment by Proxwian** [comment]
Lazy piece of shitbag

**Comment by Robocraft999** [comment]
Do it yourself instead if your really need it. I cant put up a patch if your fix it and set up a pull request

**Comment by Robocraft999** [comment]
1.18.2 Backport is now available. Have fun
