### ISSUE TITLE
1.18.2 Crashes On Startup

### ISSUE THREAD

**Issue by toErIpNid** [Robocraft999/CreateGoggles#9]
Crash Log: https://pastebin.com/8ypp0gSJ

Forge Ver: 40.2.9

Mod Ver: 0.5.1a

**Comment by Robocraft999** [comment]
Create Goggles does not support 0.5.1 and won't support it on 1.18.2 because it's discontinued there. Sorry

**Comment by Robocraft999** [comment]
1.18.2 Backport is here but will not receive any more updates
